app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as'   => 'blog'
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@show',
    'as'   => 'blog.show'
]);

Route::get('/category/{category}', [
    'uses' => 'BlogController@category',
    'as'   => 'category'
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{
    protected $dates = ['published_at'];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }


    public function getImageUrlAttribute($value)
    {
        $imageUrl = "";

        if ( ! is_null($this->image))
        {
            $imagePath = public_path() . "/img/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("img/" . $this->image);
        }

        return $imageUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function getBodyHtmlAttribute($value)
    {
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function getExcerptHtmlAttribute($value)
    {
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }


    public function scopeLatestFirst($query)
    {
        return $query->orderBy('published_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where("published_at", "<=", Carbon::now());
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Post;
use App\Category;

class BlogController extends Controller
{
    protected $limit = 3;

    public function index()
    {
        $posts = Post::with('author')
                    ->latestFirst()
                    ->published()
                    ->simplePaginate($this->limit);

        return view("blog.index", compact('posts'));
    }

    public function category(Category $category)
    {
        $categoryName = $category->title;

        // \DB::enableQueryLog();
        $posts = $category->posts()
                          ->with('author')
                          ->latestFirst()
                          ->published()
                          ->simplePaginate($this->limit);

         return view("blog.index", compact('posts', 'categoryName'));

        //  dd(\DB::getQueryLog());
    }

    public function show(Post $post)
    {
        return view("blog.show", compact('post'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

resources/views/blog/comments.blade.php
<article class="post-comments">
  <h3><i class="fa fa-comments"></i> 5 Comments</h3>

  <div class="comment-body padding-10">
    <ul class="comments-list">
      <li class="comment-item">
        <div class="comment-heading clearfix">
          <div class="comment-author-meta">
            <h4>John Doe <small>January 14, 2016</small></h4>
          </div>
        </div>
        <div class="comment-content">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
          <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
        </div>
      </li>

      <li class="comment-item">
        <div class="comment-heading clearfix">
          <div class="comment-author-meta">
            <h4>John Doe <small>January 14, 2016</small></h4>
          </div>
        </div>
        <div class="comment-content">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
          <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

          <ul class="comments-list-children">
            <li class="comment-item">
              <div class="comment-heading clearfix">
                <div class="comment-author-meta">
                  <h4>John Doe <small>January 14, 2016</small></h4>
                </div>
              </div>
              <div class="comment-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
              </div>
            </li>

            <li class="comment-item">
              <div class="comment-heading clearfix">
                <div class="comment-author-meta">
                  <h4>John Doe <small>January 14, 2016</small></h4>
                </div>
              </div>
              <div class="comment-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>

                <ul class="comments-list-children">
                  <li class="comment-item">
                    <div class="comment-heading clearfix">
                      <div class="comment-author-meta">
                        <h4>John Doe <small>January 14, 2016</small></h4>
                      </div>
                    </div>
                    <div class="comment-content">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio nesciunt nulla est, atque ratione nostrum cumque ducimus maxime, amet enim tempore ipsam. Id ea, veniam ipsam perspiciatis assumenda magnam doloribus!</p>
                      <p>Quibusdam iusto culpa, necessitatibus, libero sequi quae commodi ea ab non facilis enim vitae inventore laborum hic unde esse debitis. Adipisci nostrum reprehenderit explicabo, non molestias aliquid quibusdam tempore. Vel.</p>
                    </div>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </li>
    </ul>

  </div>

  <div class="comment-footer padding-10">
    <h3>Leave a comment</h3>
    <form>
      <div class="form-group required">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control">
      </div>
      <div class="form-group required">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" class="form-control">
      </div>
      <div class="form-group">
        <label for="website">Website</label>
        <input type="text" name="website" id="website" class="form-control">
      </div>
      <div class="form-group required">
        <label for="comment">Comment</label>
        <textarea name="comment" id="comment" rows="6" class="form-control"></textarea>
      </div>
      <div class="clearfix">
        <div class="pull-left">
          <button type="submit" class="btn btn-lg btn-success">Submit</button>
        </div>
        <div class="pull-right">
          <p class="text-muted">
            <span class="required">*</span>
            <em>Indicates required fields</em>
          </p>
        </div>
      </div>
    </form>
  </div>

</article>

resources/views/blog/index.blade.php
@extends('layouts.main')

@section('content')

<div class="container">
  <div class="row">
    <div class="col-md-8">
      @if (! $posts->count())
      <div class="alert alert-warning">
        <p>Nothing Found</p>
      </div>
      @else
      @if (isset($categoryName))
      <div class="alert alert-info">
        <p>Category: <strong>{{ $categoryName }}</strong></p>
      </div>
      @endif

      @foreach($posts as $post)

      <article class="post-item">
        @if ($post->image_url)
        <div class="post-item-image">
          <a href="{{ route('blog.show', $post->slug) }}">
            <img src="{{ $post->image_url }}" alt="">
          </a>
        </div>
        @endif

        <div class="post-item-body">
          <div class="padding-10">
            <h2><a href="{{ route('blog.show', $post->slug) }}">{{ $post->title }}</a></h2>
            {!! $post->excerpt_html !!}
          </div>

          <div class="post-meta padding-10 clearfix">
            <div class="pull-left">
              <ul class="post-meta-group">
                <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name }}</a></li>
                <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
              </ul>
            </div>
            <div class="pull-right">
              <a href="{{ route('blog.show', $post->slug) }}">Continue Reading &raquo;</a>
            </div>
          </div>
        </div>
      </article>

      @endforeach

      @endif

      <nav>
        {{ $posts->links() }}
      </nav>
    </div>

    @include('layouts.sidebar')
  </div>
</div>

@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')

@section('content')

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <article class="post-item post-detail">
        @if ($post->image_url)
        <div class="post-item-image">
          <img src="{{ $post->image_url }}" alt="{{ $post->title }}">
        </div>
        @endif

        <div class="post-item-body">
          <div class="padding-10">
            <h1>{{ $post->title }}</h1>

            <div class="post-meta no-border">
              <ul class="post-meta-group">
                <li><i class="fa fa-user"></i><a href="#"> {{ $post->author->name }}</a></li>
                <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                <li><i class="fa fa-tags"></i><a href="#"> Blog</a></li>
                <li><i class="fa fa-comments"></i><a href="#">4 Comments</a></li>
              </ul>
            </div>

            {!! $post->body_html !!}
          </div>
        </div>
      </article>

      <article class="post-author padding-10">
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img alt="Author 1" src="/img/author.jpg" class="media-object">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><a href="#">{{ $post->author->name }}</a></h4>
            <div class="post-author-count">
              <a href="#">
                <i class="fa fa-clone"></i>
                90 posts
              </a>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad aut sunt cum, mollitia excepturi neque sint magnam minus aliquam, voluptatem, labore quis praesentium eum quae dolorum temporibus consequuntur! Non.</p>
          </div>
        </div>
      </article>

      <!-- comments here -->
    </div>

    @include('layouts.sidebar')
  </div>
</div>

@endsection

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>MyBlog | My Awesome Blog</title>

    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.css">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#the-navbar-collapse" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyBlog</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="the-navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="{{ route('blog') }}">Blog</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav>
    </header>

    @yield('content')

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <p class="copyright">&copy; <?php echo date('Y'); ?> Prorock Web Productions</p>
          </div>
          <div class="col-md-4">
            <nav>
              <ul class="social-icons">
                <li><a href="#" class="i fa fa-facebook"></a></li>
                <li><a href="#" class="i fa fa-twitter"></a></li>
                <li><a href="#" class="i fa fa-google-plus"></a></li>
                <li><a href="#" class="i fa fa-github"></a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </footer>

    <script src="/js/bootstrap.min.js"></script>
  </body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="col-md-4">
  <aside class="right-sidebar">
    <!--
    <div class="search-widget">
        <div class="input-group">
          <input type="text" class="form-control input-lg" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-lg btn-default" type="button">
                <i class="fa fa-search"></i>
            </button>
          </span>
        </div>
    </div>
    -->

    <div class="widget">
      <div class="widget-heading">
        <h4>Categories</h4>
      </div>
      <div class="widget-body">
        <ul class="categories">
          @foreach ($categories as $category)
          <li>
            <a href="{{ route('category', $category->slug) }}"><i class="fa fa-angle-right"></i> {{ $category->title }}</a>
            <span class="badge pull-right">{{ $category->posts->count() }}</span>
          </li>
          @endforeach
        </ul>
      </div>
    </div>

    <div class="widget">
      <div class="widget-heading">
        <h4>Popular Posts</h4>
      </div>
      <div class="widget-body">
        <ul class="popular-posts">
          <li>
            <div class="post-image">
              <a href="#">
                <img src="/img/Post_Image_5_thumb.jpg" />
              </a>
            </div>
            <div class="post-body">
              <h6><a href="#">Blog Post #5</a></h6>
              <div class="post-meta">
                <span>36 minutes ago</span>
              </div>
            </div>
          </li>
          <li>
            <div class="post-image">
              <a href="#">
                <img src="/img/Post_Image_4_thumb.jpg" />
              </a>
            </div>
            <div class="post-body">
              <h6><a href="#">Blog Post #4</a></h6>
              <div class="post-meta">
                <span>36 minutes ago</span>
              </div>
            </div>
          </li>
          <li>
            <div class="post-image">
              <a href="#">
                <img src="/img/Post_Image_3_thumb.jpg" />
              </a>
            </div>
            <div class="post-body">
              <h6><a href="#">Blog Post #3</a></h6>
              <div class="post-meta">
                <span>36 minutes ago</span>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <!--
    <div class="widget">
        <div class="widget-heading">
            <h4>Tags</h4>
        </div>
        <div class="widget-body">
            <ul class="tags">
                <li><a href="#">PHP</a></li>
                <li><a href="#">Codeigniter</a></li>
                <li><a href="#">Yii</a></li>
                <li><a href="#">Laravel</a></li>
                <li><a href="#">Ruby on Rails</a></li>
                <li><a href="#">jQuery</a></li>
                <li><a href="#">Vue Js</a></li>
                <li><a href="#">React Js</a></li>
            </ul>
        </div>
    </div>

    -->
  </aside>
</div>